=== jordirocha/1rDAW/M04 Lenguaje De Marcas/UF1/NF2/Examen NF2/XMLXSD/NFL.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="NFL">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="super_bowl" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="super_bowl">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="date" type="xs:date"/>
                <xs:element name="city" type="xs:string"/>
                <xs:element name="zip_code">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z]{2}-[0-9]{3}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element ref="team" maxOccurs="2"/>
                <xs:element ref="entertiment" />
                <xs:element ref="edition"/>                     
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="team">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="points" type="xs:positiveInteger"/>
                <xs:element name="winner" type="xs:token" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="conference" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="NFC|AFC"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="entertiment">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="group" type="xs:string" minOccurs="0"/>
                <xs:element name="artist" type="xs:string" minOccurs="0" maxOccurs="3"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>    
    
    <xs:element name="edition">
        <xs:complexType>
            <xs:simpleContent>               
                <xs:extension base="xs:positiveInteger">
                    <xs:attribute name="year">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minInclusive value="2016"/>
                                <xs:maxInclusive value="2020"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
   
</xs:schema>

=== jordirocha/1rDAW/M04 Lenguaje De Marcas/UF1/NF2/Examen NF2/XMLXSD/DAW_NFL.xml
<?xml version="1.0" encoding="UTF-8"?>
<NFL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NFL.xsd">
    <super_bowl>

        <date>2016-02-07</date>
        <city>Santa Clara</city>
        <zip_code>CA-240</zip_code>
    
        <team conference="AFC">
            <name>Denver Broncos</name>
            <points>24</points>
            <winner/>
        </team>
    
        <team conference="NFC">
            <name>Carolina Panthers</name>
            <points>10</points>
        </team>
    
        <entertiment>
            <group>Coldplay</group>
            <artist>Beyonce</artist>
        </entertiment>
        <edition year="2016">50</edition>
    </super_bowl>
  
    <super_bowl>
    
        <date>2017-02-05</date>
        <city>Houston</city>
        <zip_code>TX-430</zip_code>
    
        <team conference="AFC">
            <name>New England Patriots</name>
            <points>34</points>
            <winner/>
        </team>
    
        <team conference="NFC">
            <name>Atlanta Falcons</name>
            <points>28</points>
        </team>
        <entertiment>
            <artist>Lady Gaga</artist>
        </entertiment>
        <edition year="2017">51</edition>
    </super_bowl>
  
    <super_bowl>
    
        <date>2018-02-04</date>
        <city>Minneapolis</city>
        <zip_code>MA-076</zip_code>
    
        <team conference="NFC">
            <name>Philadelphia Eagles</name>
            <points>41</points>
            <winner/>
        </team>
    
        <team conference="AFC">
            <name>New England Patriots</name>
            <points>33</points>
        </team>
    
        <entertiment>
            <artist>Justin Timberlake</artist>
        </entertiment>
        <edition year="2018">52</edition>
    </super_bowl>
  
    <super_bowl>
    
        <date>2019-02-03</date>
        <city>Atlanta</city>
        <zip_code>GE-127</zip_code>
    
        <team conference="AFC">
            <name>New England Patriots</name>
            <points>13</points>
            <winner/>
        </team>
    
        <team conference="NFC">
            <name>Los Angeles Rams</name>
            <points>3</points>
        </team>
    
        <entertiment>
            <group>Maroon 5</group>
        </entertiment>
        <edition year="2019">53</edition>
    </super_bowl>
</NFL>
